spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/task_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

# 配置日志
logging:
  level:
    root: warn
    top.mqxu.boot.mapper: trace
